"""
Week 07 INDIVIDUAL ASSIGNMENT -- Software Allowlist Audit
ITIA 1510 Cybersecurity Automation

Tests for the functions in allowlist_audit.py. Do not edit this file.

Run it from the folder that holds allowlist_audit.py, approved.txt and
inventory.txt:

    python -m unittest test_allowlist_audit -v

Some tests pass before you start, because a placeholder happens to return the
right answer for that one case. A green test is only worth something once you
have written the function.

Every test has a comment above it saying what it checks. When one fails, read
that comment first.

The report TODOs, 14 through 19, are not tested here. Check those against the
table in the assignment.
"""

import os
import unittest

try:
    import allowlist_audit as aa
except ModuleNotFoundError:
    # the instructor copy of the program keeps its week08_ name
    import week08_individual_allowlist_audit as aa


class TestLoadApproved(unittest.TestCase):
    """TODO 1: load_approved."""

    # approved.txt has 9 programs, 2 comment lines and 1 blank line.
    def test_nine_programs(self) -> None:
        self.assertEqual(len(aa.load_approved("approved.txt")), 9)

    # The first program, with no newline on the end.
    def test_first_program_is_stripped(self) -> None:
        self.assertEqual(aa.load_approved("approved.txt")[0], "Chrome")

    # A program with a space in its name is one entry.
    def test_name_with_a_space(self) -> None:
        self.assertIn("Microsoft Word", aa.load_approved("approved.txt"))

    # The blank line is not in the list.
    def test_blank_line_is_skipped(self) -> None:
        self.assertNotIn("", aa.load_approved("approved.txt"))

    # No line that starts with # is in the list.
    def test_comment_lines_are_skipped(self) -> None:
        for program in aa.load_approved("approved.txt"):
            self.assertFalse(program.startswith("#"))


class TestLoadInventory(unittest.TestCase):
    """TODO 2 and TODO 3: load_inventory."""

    # 20 lines: 18 good records, 1 blank line, 1 line with no comma.
    def test_eighteen_records(self) -> None:
        self.assertEqual(len(aa.load_inventory("inventory.txt")), 18)

    # Each record is a dictionary with a host and a program.
    def test_first_record(self) -> None:
        self.assertEqual(aa.load_inventory("inventory.txt")[0], {"host": "lab-01", "program": "Chrome"})

    # The last record, with no newline on the end of the program.
    def test_last_record_is_stripped(self) -> None:
        self.assertEqual(aa.load_inventory("inventory.txt")[-1], {"host": "lab-06", "program": "TeamViewer"})

    # The line "lab-05" has no comma, so it is not a record.
    def test_line_without_a_comma_is_skipped(self) -> None:
        for record in aa.load_inventory("inventory.txt"):
            self.assertNotEqual(record["host"], "lab-05")


class TestCountBadLines(unittest.TestCase):
    """TODO 4: count_bad_lines."""

    # Only "lab-05" is bad. The blank line is skipped but not counted as bad.
    def test_one_bad_line(self) -> None:
        self.assertEqual(aa.count_bad_lines("inventory.txt"), 1)


class TestIsApproved(unittest.TestCase):
    """TODO 5: is_approved."""

    def test_approved_program(self) -> None:
        self.assertTrue(aa.is_approved("Zoom", ["Chrome", "Zoom"]))

    def test_program_not_on_the_list(self) -> None:
        self.assertFalse(aa.is_approved("Steam", ["Chrome", "Zoom"]))


class TestFindUnapproved(unittest.TestCase):
    """TODO 6: find_unapproved."""

    # Only the record whose program is not on the list comes back.
    def test_small_list(self) -> None:
        inventory = [{"host": "a", "program": "Chrome"}, {"host": "b", "program": "Steam"}]
        self.assertEqual(aa.find_unapproved(inventory, ["Chrome"]), [{"host": "b", "program": "Steam"}])

    # The real files: 7 programs are not approved.
    def test_real_files(self) -> None:
        unapproved = aa.find_unapproved(aa.load_inventory("inventory.txt"), aa.load_approved("approved.txt"))
        self.assertEqual(len(unapproved), 7)


class TestCountByHost(unittest.TestCase):
    """TODO 7: count_by_host."""

    # Two records for a, one for b.
    def test_counts(self) -> None:
        records = [{"host": "a", "program": "x"}, {"host": "b", "program": "y"}, {"host": "a", "program": "z"}]
        self.assertEqual(aa.count_by_host(records), {"a": 2, "b": 1})

    # No records gives an empty dictionary.
    def test_empty(self) -> None:
        self.assertEqual(aa.count_by_host([]), {})


class TestHostsAtOrAbove(unittest.TestCase):
    """TODO 8: hosts_at_or_above."""

    # Exactly the limit counts. The answer is sorted.
    def test_limit_counts_and_sorted(self) -> None:
        self.assertEqual(aa.hosts_at_or_above({"lab-06": 2, "lab-01": 1, "lab-03": 3}, 2), ["lab-03", "lab-06"])

    # Nobody at the limit gives an empty list.
    def test_nobody(self) -> None:
        self.assertEqual(aa.hosts_at_or_above({"lab-01": 1}, 2), [])


class TestUniquePrograms(unittest.TestCase):
    """TODO 9: unique_programs."""

    # uTorrent is on two computers but is listed once. The answer is sorted.
    def test_each_program_once(self) -> None:
        records = [{"host": "a", "program": "uTorrent"}, {"host": "b", "program": "Steam"},
                   {"host": "c", "program": "uTorrent"}]
        self.assertEqual(aa.unique_programs(records), ["Steam", "uTorrent"])


class TestPercentApproved(unittest.TestCase):
    """TODO 10: percent_approved."""

    # 11 of 18 approved: 61.1.
    def test_real_numbers(self) -> None:
        self.assertEqual(aa.percent_approved(18, 7), 61.1)

    # Nothing wrong: 100.0.
    def test_all_approved(self) -> None:
        self.assertEqual(aa.percent_approved(10, 0), 100.0)

    # No records at all: 0.0, not a crash.
    def test_zero_total(self) -> None:
        self.assertEqual(aa.percent_approved(0, 0), 0.0)


class TestAuditStatus(unittest.TestCase):
    """TODO 11: audit_status."""

    # 90 is the bottom of PASS.
    def test_90_is_pass(self) -> None:
        self.assertEqual(aa.audit_status(90.0), "PASS")

    # 75 is the bottom of WARNING.
    def test_75_is_warning(self) -> None:
        self.assertEqual(aa.audit_status(75.0), "WARNING")

    # Just under 90 is still WARNING.
    def test_89_9_is_warning(self) -> None:
        self.assertEqual(aa.audit_status(89.9), "WARNING")

    def test_61_1_is_fail(self) -> None:
        self.assertEqual(aa.audit_status(61.1), "FAIL")


class TestWriteReport(unittest.TestCase):
    """TODO 12: write_report."""

    def tearDown(self) -> None:
        if os.path.exists("test_report.txt"):
            os.remove("test_report.txt")

    # Each string becomes one line of the file.
    def test_lines_are_written(self) -> None:
        aa.write_report("test_report.txt", ["one", "two"])
        with open("test_report.txt", "r") as f:
            self.assertEqual(f.read(), "one\ntwo\n")

    # Write mode replaces what was there, so writing twice leaves only the second report.
    def test_second_write_replaces_the_first(self) -> None:
        aa.write_report("test_report.txt", ["old"])
        aa.write_report("test_report.txt", ["new"])
        with open("test_report.txt", "r") as f:
            self.assertEqual(f.read(), "new\n")


class TestAppendHistory(unittest.TestCase):
    """TODO 13: append_history, the function that is finished and wrong."""

    def tearDown(self) -> None:
        if os.path.exists("test_history.log"):
            os.remove("test_history.log")

    # Two calls give two lines. With "w", the second call erases the first.
    def test_two_calls_keep_both_lines(self) -> None:
        aa.append_history("test_history.log", "first run")
        aa.append_history("test_history.log", "second run")
        with open("test_history.log", "r") as f:
            self.assertEqual(f.readlines(), ["first run\n", "second run\n"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
